using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;
//Code generated by Aashvija S Upadhya
public partial class ChildrenInfo : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection(@"Data Source=DAMONNAHARIS\TRINA;Initial Catalog=TestDB1;Integrated Security=True");
        con.Open();
        if (con.State == System.Data.ConnectionState.Open)
        {
            string session_user = Session["USER_NAME"].ToString();
            Person CurrenntUser = new Person();
            CurrenntUser = PersonInfoGetter.GetPersonInfoByUsername(session_user);

            string r = "insert into Child( lname, fname, sex, DOB, specialNeed, pid)values('" + TextBox2.Text.ToString() + "','" + TextBox1.Text.ToString() + "','" + DropDownList1.Text.ToString() + "','" + TextBox3.Text.ToString() + "','" + TextBox4.Text.ToString() + "', '"+CurrenntUser.Pid+"')";
            SqlCommand cmd = new SqlCommand(r, con);
            cmd.ExecuteNonQuery();
            con.Close();

            Response.Redirect("ViewChildProfile.aspx");
        }
    }


    protected void Button2_Click(object sender, EventArgs e)
    {
        Response.Redirect("ChildrenInfo.aspx");
    }

    protected void Button3_Click(object sender, EventArgs e)
    {
        Response.Redirect("NewHome.aspx");
    }
}