using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;
//Code generated by Aashvija S Upadhya
public partial class UserNameRegistration : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        string username1 = TextBox1.Text;
        Session["Username1"] = username1.ToString();
       

        lblname.Text = Convert.ToString(Session["Username"]);
             
    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        SqlConnection con = new SqlConnection(@"Data Source=DAMONNAHARIS\TRINA;Initial Catalog=TestDB1;Integrated Security=True");
        con.Open();
        string checkuser = "select count(*) from Persons where UserName='" + TextBox1.Text.ToString() + "'";
        SqlCommand com = new SqlCommand(checkuser, con);
        int temp = Convert.ToInt32(com.ExecuteScalar().ToString());
        if (temp == 1)
        {
            Response.Write("User already exists");
        }


        else
        {

            if (lblname.Text != "")
            {
                try
                {
                    SqlConnection con1 = new SqlConnection(@"Data Source=DAMONNAHARIS\TRINA;Initial Catalog=TestDB1;Integrated Security=True");
                    con1.Open();
                    if (con1.State == System.Data.ConnectionState.Open)
                    {
                        string s = "Update Persons set UserName='" + TextBox1.Text + "', Password ='" + TextBox2.Text + "' where Firstname = '" + lblname.Text + "'";
                        SqlCommand cmd = new SqlCommand(s, con1);
                        cmd.ExecuteNonQuery();
                        con1.Close();
                        Response.Redirect("Login.aspx");
                    }
                }
                catch (Exception ex)
                {
                    Response.Write("Error:" + ex.ToString());
                }

            }
        }
    }
}